name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-client:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./PingClient.Tests
      run: dotnet restore
    - name: Build
      working-directory: ./PingClient.Tests
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./PingClient.Tests
      run: dotnet test --no-build --verbosity normal

  test-server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./PingServer.Tests
      run: dotnet restore
    - name: Build
      working-directory: ./PingServer.Tests
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./PingServer.Tests
      run: dotnet test --no-build --verbosity normal

  format-client-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./PingClient.Tests
      run: dotnet restore
    - name: Format
      working-directory: ./PingClient.Tests
      run: dotnet format --verify-no-changes --verbosity diagnostic

  format-server-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./PingServer.Tests
      run: dotnet restore
    - name: Format
      working-directory: ./PingServer.Tests
      run: dotnet format --verify-no-changes --verbosity diagnostic

  format-client-src:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./PingClient
      run: dotnet restore
    - name: Format
      working-directory: ./PingClient
      run: dotnet format --verify-no-changes --verbosity diagnostic

  format-server-src:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./PingServer
      run: dotnet restore
    - name: Format
      working-directory: ./PingServer
      run: dotnet format --verify-no-changes --verbosity diagnostic
